name: rann_github
description: A github client dev by rann studio.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  flutter_redux: ^0.5.3
  json_annotation: ^2.4.0
  redux_epics: ^0.10.6
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^3.1.0
  dio: ^2.1.7
  connectivity: ^0.4.3+2
  event_bus: ^1.1.0
  android_intent: ^0.3.0+2
  flare_flutter: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  json_serializable: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/image/welcome.png
    - assets/image/logo.png
    - assets/file/rejection.json
    - assets/file/rejection2.json
    - assets/file/flare_flutter_logo_.flr
    - assets/file/loading_world_now.flr
    - assets/file/Space-Demo.flr


  fonts:
    - family: HubIconFont
      fonts:
        - asset: assets/font/iconfont.ttf
