name: rann_github
description: A github client dev by rann studio.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  flutter_redux: ^0.5.3
  json_annotation: ^2.4.0
  redux_epics: ^0.10.6
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_lottie:
    git:
      url: https://github.com/CarSmallGuo/flutter_lottie.git
      ref: 3adb18f2e2a45b8dbdebc0437e9a4db3f6ff32b8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  json_serializable: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/welcome.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
